name: Maven Build and Test

# Se ejecuta en cada push y pull request al branch `main`
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out el código del repositorio
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Configura Java (por ejemplo, OpenJDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # 3. Configura Maven
      - name: Set up Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '3.8.1'

      # 4. Ejecuta Maven para compilar el proyecto y correr las pruebas
      - name: Build and Test with Maven
        run: mvn clean install

      # 5. (Opcional) Si tienes notificaciones o despliegues, puedes agregar aquí los pasos adicionales.
